/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin V5.28.                           *
*        Compiled Jan 30 2015, 16:40:04                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: folder                                                *
* Dimensions:  30 * 30                                               *
* NumColors:   None, only alpha channel                              *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmfolder;

static GUI_CONST_STORAGE unsigned char _acfolder[] = {
  /* RLE: 156 Pixels @ 000,000 */ 156, 0xFF, 
  /* ABS: 002 Pixels @ 006,005 */ 0, 2, 0xC2, 0x0B, 
  /* RLE: 006 Pixels @ 008,005 */ 6, 0x00, 
  /* ABS: 002 Pixels @ 014,005 */ 0, 2, 0x0B, 0xC4, 
  /* RLE: 020 Pixels @ 016,005 */ 20, 0xFF, 
  /* RLE: 001 Pixels @ 006,006 */ 1, 0x60, 
  /* RLE: 008 Pixels @ 007,006 */ 8, 0x00, 
  /* RLE: 001 Pixels @ 015,006 */ 1, 0x60, 
  /* RLE: 020 Pixels @ 016,006 */ 20, 0xFF, 
  /* RLE: 001 Pixels @ 006,007 */ 1, 0x20, 
  /* RLE: 008 Pixels @ 007,007 */ 8, 0x00, 
  /* RLE: 001 Pixels @ 015,007 */ 1, 0x20, 
  /* RLE: 017 Pixels @ 016,007 */ 17, 0xFF, 
  /* RLE: 001 Pixels @ 003,008 */ 1, 0x49, 
  /* RLE: 022 Pixels @ 004,008 */ 22, 0x00, 
  /* RLE: 001 Pixels @ 026,008 */ 1, 0x49, 
  /* RLE: 006 Pixels @ 027,008 */ 6, 0xFF, 
  /* RLE: 024 Pixels @ 003,009 */ 24, 0x00, 
  /* RLE: 064 Pixels @ 027,009 */ 64, 0xFF, 
  /* RLE: 001 Pixels @ 001,012 */ 1, 0x13, 
  /* RLE: 026 Pixels @ 002,012 */ 26, 0x00, 
  /* ABS: 004 Pixels @ 028,012 */ 0, 4, 0x12, 0xFF, 0xFF, 0x3B, 
  /* RLE: 026 Pixels @ 002,013 */ 26, 0x00, 
  /* ABS: 004 Pixels @ 028,013 */ 0, 4, 0x3B, 0xFF, 0xFF, 0x62, 
  /* RLE: 026 Pixels @ 002,014 */ 26, 0x00, 
  /* ABS: 004 Pixels @ 028,014 */ 0, 4, 0x62, 0xFF, 0xFF, 0x89, 
  /* RLE: 026 Pixels @ 002,015 */ 26, 0x00, 
  /* ABS: 004 Pixels @ 028,015 */ 0, 4, 0x88, 0xFF, 0xFF, 0xB1, 
  /* RLE: 026 Pixels @ 002,016 */ 26, 0x00, 
  /* ABS: 004 Pixels @ 028,016 */ 0, 4, 0xB1, 0xFF, 0xFF, 0xD8, 
  /* RLE: 026 Pixels @ 002,017 */ 26, 0x00, 
  /* ABS: 005 Pixels @ 028,017 */ 0, 5, 0xD7, 0xFF, 0xFF, 0xFA, 0x05, 
  /* RLE: 024 Pixels @ 003,018 */ 24, 0x00, 
  /* ABS: 006 Pixels @ 027,018 */ 0, 6, 0x05, 0xFA, 0xFF, 0xFF, 0xFF, 0x28, 
  /* RLE: 024 Pixels @ 003,019 */ 24, 0x00, 
  /* RLE: 001 Pixels @ 027,019 */ 1, 0x27, 
  /* RLE: 004 Pixels @ 028,019 */ 4, 0xFF, 
  /* RLE: 001 Pixels @ 002,020 */ 1, 0x4E, 
  /* RLE: 024 Pixels @ 003,020 */ 24, 0x00, 
  /* RLE: 001 Pixels @ 027,020 */ 1, 0x4E, 
  /* RLE: 004 Pixels @ 028,020 */ 4, 0xFF, 
  /* RLE: 001 Pixels @ 002,021 */ 1, 0x77, 
  /* RLE: 024 Pixels @ 003,021 */ 24, 0x00, 
  /* RLE: 001 Pixels @ 027,021 */ 1, 0x76, 
  /* RLE: 004 Pixels @ 028,021 */ 4, 0xFF, 
  /* RLE: 001 Pixels @ 002,022 */ 1, 0x9D, 
  /* RLE: 024 Pixels @ 003,022 */ 24, 0x00, 
  /* RLE: 001 Pixels @ 027,022 */ 1, 0x9C, 
  /* RLE: 004 Pixels @ 028,022 */ 4, 0xFF, 
  /* RLE: 001 Pixels @ 002,023 */ 1, 0xC4, 
  /* RLE: 024 Pixels @ 003,023 */ 24, 0x00, 
  /* RLE: 001 Pixels @ 027,023 */ 1, 0xC4, 
  /* RLE: 004 Pixels @ 028,023 */ 4, 0xFF, 
  /* RLE: 001 Pixels @ 002,024 */ 1, 0xEC, 
  /* RLE: 024 Pixels @ 003,024 */ 24, 0x00, 
  /* RLE: 001 Pixels @ 027,024 */ 1, 0xEC, 
  /* RLE: 005 Pixels @ 028,024 */ 5, 0xFF, 
  /* RLE: 001 Pixels @ 003,025 */ 1, 0x47, 
  /* RLE: 022 Pixels @ 004,025 */ 22, 0x00, 
  /* RLE: 001 Pixels @ 026,025 */ 1, 0x48, 
  /* RLE: 123 Pixels @ 027,025 */ 123, 0xFF, 
  0
};  // 157 bytes for 900 pixels

GUI_CONST_STORAGE GUI_BITMAP bmfolder = {
  30, // xSize
  30, // ySize
  30, // BytesPerLine
  GUI_COMPRESS_RLE8, // BitsPerPixel
  (unsigned char *)_acfolder,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_RLEALPHA
};

/*************************** End of file ****************************/
