/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin V5.28.                           *
*        Compiled Jan 30 2015, 16:40:04                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: music                                                 *
* Dimensions:  30 * 30                                               *
* NumColors:   None, only alpha channel                              *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmmusic;

static GUI_CONST_STORAGE unsigned char _acmusic[] = {
  /* RLE: 111 Pixels @ 000,000 */ 111, 0xFF, 
  /* ABS: 004 Pixels @ 021,003 */ 0, 4, 0xF7, 0xB7, 0x6C, 0x24, 
  /* RLE: 023 Pixels @ 025,003 */ 23, 0xFF, 
  /* ABS: 007 Pixels @ 018,004 */ 0, 7, 0xDB, 0x93, 0x4A, 0x0A, 0x00, 0x00, 0x00, 
  /* RLE: 019 Pixels @ 025,004 */ 19, 0xFF, 
  /* ABS: 004 Pixels @ 014,005 */ 0, 4, 0xF7, 0xB7, 0x6C, 0x24, 
  /* RLE: 007 Pixels @ 018,005 */ 7, 0x00, 
  /* RLE: 016 Pixels @ 025,005 */ 16, 0xFF, 
  /* ABS: 004 Pixels @ 011,006 */ 0, 4, 0xDB, 0x93, 0x4A, 0x0A, 
  /* RLE: 010 Pixels @ 015,006 */ 10, 0x00, 
  /* RLE: 016 Pixels @ 025,006 */ 16, 0xFF, 
  /* RLE: 014 Pixels @ 011,007 */ 14, 0x00, 
  /* RLE: 016 Pixels @ 025,007 */ 16, 0xFF, 
  /* RLE: 010 Pixels @ 011,008 */ 10, 0x00, 
  /* ABS: 004 Pixels @ 021,008 */ 0, 4, 0x08, 0x48, 0x00, 0x00, 
  /* RLE: 016 Pixels @ 025,008 */ 16, 0xFF, 
  /* RLE: 007 Pixels @ 011,009 */ 7, 0x00, 
  /* ABS: 007 Pixels @ 018,009 */ 0, 7, 0x24, 0x6C, 0xB5, 0xF5, 0xFF, 0x00, 0x00, 
  /* RLE: 016 Pixels @ 025,009 */ 16, 0xFF, 
  /* RLE: 003 Pixels @ 011,010 */ 3, 0x00, 
  /* ABS: 004 Pixels @ 014,010 */ 0, 4, 0x08, 0x48, 0x93, 0xDB, 
  /* RLE: 005 Pixels @ 018,010 */ 5, 0xFF, 
  /* ABS: 002 Pixels @ 023,010 */ 0, 2, 0x00, 0x00, 
  /* RLE: 016 Pixels @ 025,010 */ 16, 0xFF, 
  /* ABS: 004 Pixels @ 011,011 */ 0, 4, 0x00, 0x00, 0xB5, 0xF5, 
  /* RLE: 008 Pixels @ 015,011 */ 8, 0xFF, 
  /* ABS: 002 Pixels @ 023,011 */ 0, 2, 0x00, 0x00, 
  /* RLE: 016 Pixels @ 025,011 */ 16, 0xFF, 
  /* ABS: 002 Pixels @ 011,012 */ 0, 2, 0x00, 0x00, 
  /* RLE: 010 Pixels @ 013,012 */ 10, 0xFF, 
  /* ABS: 002 Pixels @ 023,012 */ 0, 2, 0x00, 0x00, 
  /* RLE: 016 Pixels @ 025,012 */ 16, 0xFF, 
  /* ABS: 002 Pixels @ 011,013 */ 0, 2, 0x00, 0x00, 
  /* RLE: 010 Pixels @ 013,013 */ 10, 0xFF, 
  /* ABS: 002 Pixels @ 023,013 */ 0, 2, 0x00, 0x00, 
  /* RLE: 016 Pixels @ 025,013 */ 16, 0xFF, 
  /* ABS: 002 Pixels @ 011,014 */ 0, 2, 0x00, 0x00, 
  /* RLE: 010 Pixels @ 013,014 */ 10, 0xFF, 
  /* ABS: 002 Pixels @ 023,014 */ 0, 2, 0x00, 0x00, 
  /* RLE: 016 Pixels @ 025,014 */ 16, 0xFF, 
  /* ABS: 002 Pixels @ 011,015 */ 0, 2, 0x00, 0x00, 
  /* RLE: 010 Pixels @ 013,015 */ 10, 0xFF, 
  /* ABS: 002 Pixels @ 023,015 */ 0, 2, 0x00, 0x00, 
  /* RLE: 016 Pixels @ 025,015 */ 16, 0xFF, 
  /* ABS: 002 Pixels @ 011,016 */ 0, 2, 0x00, 0x00, 
  /* RLE: 010 Pixels @ 013,016 */ 10, 0xFF, 
  /* ABS: 002 Pixels @ 023,016 */ 0, 2, 0x00, 0x00, 
  /* RLE: 016 Pixels @ 025,016 */ 16, 0xFF, 
  /* ABS: 002 Pixels @ 011,017 */ 0, 2, 0x00, 0x00, 
  /* RLE: 010 Pixels @ 013,017 */ 10, 0xFF, 
  /* ABS: 002 Pixels @ 023,017 */ 0, 2, 0x00, 0x00, 
  /* RLE: 016 Pixels @ 025,017 */ 16, 0xFF, 
  /* ABS: 002 Pixels @ 011,018 */ 0, 2, 0x00, 0x00, 
  /* RLE: 010 Pixels @ 013,018 */ 10, 0xFF, 
  /* ABS: 002 Pixels @ 023,018 */ 0, 2, 0x00, 0x00, 
  /* RLE: 016 Pixels @ 025,018 */ 16, 0xFF, 
  /* ABS: 002 Pixels @ 011,019 */ 0, 2, 0x00, 0x00, 
  /* RLE: 005 Pixels @ 013,019 */ 5, 0xFF, 
  /* ABS: 007 Pixels @ 018,019 */ 0, 7, 0xF9, 0x81, 0x26, 0x0A, 0x26, 0x00, 0x00, 
  /* RLE: 016 Pixels @ 025,019 */ 16, 0xFF, 
  /* ABS: 002 Pixels @ 011,020 */ 0, 2, 0x00, 0x00, 
  /* RLE: 005 Pixels @ 013,020 */ 5, 0xFF, 
  /* RLE: 001 Pixels @ 018,020 */ 1, 0x59, 
  /* RLE: 006 Pixels @ 019,020 */ 6, 0x00, 
  /* RLE: 016 Pixels @ 025,020 */ 16, 0xFF, 
  /* ABS: 002 Pixels @ 011,021 */ 0, 2, 0x00, 0x00, 
  /* RLE: 005 Pixels @ 013,021 */ 5, 0xFF, 
  /* RLE: 001 Pixels @ 018,021 */ 1, 0x08, 
  /* RLE: 005 Pixels @ 019,021 */ 5, 0x00, 
  /* RLE: 001 Pixels @ 024,021 */ 1, 0x08, 
  /* RLE: 011 Pixels @ 025,021 */ 11, 0xFF, 
  /* ABS: 007 Pixels @ 006,022 */ 0, 7, 0xF9, 0x81, 0x26, 0x0A, 0x26, 0x00, 0x00, 
  /* RLE: 005 Pixels @ 013,022 */ 5, 0xFF, 
  /* RLE: 001 Pixels @ 018,022 */ 1, 0x59, 
  /* RLE: 005 Pixels @ 019,022 */ 5, 0x00, 
  /* RLE: 001 Pixels @ 024,022 */ 1, 0x58, 
  /* RLE: 011 Pixels @ 025,022 */ 11, 0xFF, 
  /* RLE: 001 Pixels @ 006,023 */ 1, 0x59, 
  /* RLE: 006 Pixels @ 007,023 */ 6, 0x00, 
  /* RLE: 005 Pixels @ 013,023 */ 5, 0xFF, 
  /* ABS: 007 Pixels @ 018,023 */ 0, 7, 0xF9, 0x81, 0x25, 0x08, 0x25, 0x81, 0xF9, 
  /* RLE: 011 Pixels @ 025,023 */ 11, 0xFF, 
  /* RLE: 001 Pixels @ 006,024 */ 1, 0x08, 
  /* RLE: 005 Pixels @ 007,024 */ 5, 0x00, 
  /* RLE: 001 Pixels @ 012,024 */ 1, 0x08, 
  /* RLE: 023 Pixels @ 013,024 */ 23, 0xFF, 
  /* RLE: 001 Pixels @ 006,025 */ 1, 0x59, 
  /* RLE: 005 Pixels @ 007,025 */ 5, 0x00, 
  /* RLE: 001 Pixels @ 012,025 */ 1, 0x58, 
  /* RLE: 023 Pixels @ 013,025 */ 23, 0xFF, 
  /* ABS: 007 Pixels @ 006,026 */ 0, 7, 0xF9, 0x81, 0x25, 0x08, 0x25, 0x81, 0xF9, 
  /* RLE: 107 Pixels @ 013,026 */ 107, 0xFF, 
  0
};  // 288 bytes for 900 pixels

GUI_CONST_STORAGE GUI_BITMAP bmmusic = {
  30, // xSize
  30, // ySize
  30, // BytesPerLine
  GUI_COMPRESS_RLE8, // BitsPerPixel
  (unsigned char *)_acmusic,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_RLEALPHA
};

/*************************** End of file ****************************/
